// Email Service for Certificate Verification Alerts
// This service sends email notifications when tampered certificates are detected

export class EmailService {
  constructor() {
    this.apiBaseUrl = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001/api';
  }

  // Send tampered certificate alert email
  async sendTamperedCertificateAlert(certificateData) {
    try {
      // Only attach PDF if it's not too large (less than 10MB)
      const shouldAttachPDF = certificateData.fileContent && certificateData.fileContent.length < 10000000;
      
      const emailData = {
        to: certificateData.institutionEmail || 'test@example.com',
        subject: `Tampered Certificate Detected for ${certificateData.claimedInstitution}`,
        body: this.generateEmailBody(certificateData, shouldAttachPDF),
        attachments: shouldAttachPDF ? [
          {
            filename: certificateData.fileName,
            content: certificateData.fileContent, // Base64 encoded PDF
            contentType: 'application/pdf'
          }
        ] : []
      };

      const response = await fetch(`${this.apiBaseUrl}/send-email`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(emailData)
      });

      if (!response.ok) {
        throw new Error(`Email sending failed: ${response.status}`);
      }

      const result = await response.json();
      return result;
    } catch (error) {
      console.error('Error sending tampered certificate email:', error);
      throw error;
    }
  }

  // Generate email body content
  generateEmailBody(certificateData, includePDF = true) {
    const timestamp = new Date().toLocaleString();
    
    return `
Hello Registrar,

During a verification request, a tampered certificate claiming to belong to ${certificateData.claimedInstitution} was detected.

Certificate ID: ${certificateData.certificateId || 'N/A'}
Claimed Institution: ${certificateData.claimedInstitution}
Uploaded By: ${certificateData.uploadedBy || 'Unknown'}
Reason: ${certificateData.reason || 'Certificate verification failed'}
Timestamp: ${timestamp}

Action Required:
Please review this case. The certificate is flagged as tampered.

${!includePDF ? 'Note: The certificate PDF file was too large to attach to this email. Please contact TrustEd for the file if needed.' : ''}

This alert was automatically generated by the TrustEd Verification Platform.

Regards,
TrustEd
    `.trim();
  }

  // Convert file to base64 for email attachment
  async fileToBase64(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result.split(',')[1]); // Remove data:application/pdf;base64, prefix
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  }

  // Prepare certificate data for email
  async prepareCertificateData(verificationResult, originalFile) {
    const fileContent = await this.fileToBase64(originalFile);
    
    return {
      fileName: originalFile.name,
      fileContent: fileContent,
      certificateId: verificationResult.data?.roll || verificationResult.data?.certificateId || 'N/A',
      claimedInstitution: 'Mangalayatan University', // Always use Mangalayatan University
      institutionEmail: this.getInstitutionEmail('MANGALAYATAN UNIVERSITY'), // Use Mangalayatan University email
      uploadedBy: 'TRUSTED Pvt Ltd', // You can make this dynamic
      reason: verificationResult.message || verificationResult.details || 'Certificate verification failed',
      timestamp: new Date().toISOString()
    };
  }

  // Get institution email based on university name - USING MOCK EMAILS FOR TESTING
  getInstitutionEmail(universityName) {
    const emailMap = {
      'MANGALAYATAN UNIVERSITY': 'paxave5522@camjoint.com',
      'RANCHI UNIVERSITY': 'ranchi.test@example.com', 
      'IIT DHANBAD': 'iitdhanbad.test@example.com',
      'XAVIER INSTITUTE': 'xavier.test@example.com',
      // Add more institutions as needed
    };

    const upperName = universityName?.toUpperCase();
    return emailMap[upperName] || 'test@example.com'; // Default fallback to test email
  }
}

export default EmailService;
